-- +goose Up
CREATE TABLE IF NOT EXISTS large_work_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_team_id BIGINT NOT NULL REFERENCES "Team"(id),
    created_by_user_id BIGINT NOT NULL REFERENCES "User"(id),
    title TEXT NOT NULL,
    work_type TEXT,
    start_date DATE NOT NULL,
    end_date DATE,
    work_time TEXT,
    location_text TEXT NOT NULL,
    pea_id BIGINT REFERENCES "Pea"(id),
    operation_center_id BIGINT REFERENCES "OperationCenter"(id),
    feeder_id BIGINT REFERENCES "Feeder"(id),
    station_id BIGINT REFERENCES "Station"(id),
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT large_work_items_status_check CHECK (status IN ('planned', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT large_work_items_date_range_check CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS large_work_item_teams (
    large_work_item_id BIGINT NOT NULL REFERENCES large_work_items(id) ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES "Team"(id),
    role TEXT NOT NULL,
    participant_status TEXT NOT NULL DEFAULT 'assigned',
    acknowledged_by_user_id BIGINT REFERENCES "User"(id),
    acknowledged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (large_work_item_id, team_id),
    CONSTRAINT large_work_item_teams_role_check CHECK (role IN ('owner', 'participant')),
    CONSTRAINT large_work_item_teams_participant_status_check CHECK (participant_status IN ('assigned', 'acknowledged'))
);

CREATE TABLE IF NOT EXISTS large_work_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    large_work_item_id BIGINT NOT NULL REFERENCES large_work_items(id) ON DELETE CASCADE,
    assigned_team_id BIGINT NOT NULL REFERENCES "Team"(id),
    sequence INTEGER NOT NULL,
    point_label TEXT NOT NULL,
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    work_type TEXT NOT NULL,
    work_detail TEXT,
    point_count INTEGER,
    tree_count INTEGER,
    item_count INTEGER,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'todo',
    before_photo_urls TEXT[] NOT NULL DEFAULT '{}',
    after_photo_urls TEXT[] NOT NULL DEFAULT '{}',
    completion_note TEXT,
    started_by_user_id BIGINT REFERENCES "User"(id),
    started_at TIMESTAMPTZ,
    completed_by_user_id BIGINT REFERENCES "User"(id),
    completed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT large_work_tasks_status_check CHECK (status IN ('todo', 'in_progress', 'done', 'blocked', 'cancelled')),
    CONSTRAINT large_work_tasks_sequence_positive_check CHECK (sequence > 0),
    CONSTRAINT large_work_tasks_point_count_non_negative_check CHECK (point_count IS NULL OR point_count >= 0),
    CONSTRAINT large_work_tasks_tree_count_non_negative_check CHECK (tree_count IS NULL OR tree_count >= 0),
    CONSTRAINT large_work_tasks_item_count_non_negative_check CHECK (item_count IS NULL OR item_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_large_work_items_owner_start_date ON large_work_items (owner_team_id, start_date);
CREATE INDEX IF NOT EXISTS idx_large_work_items_date_range ON large_work_items (start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_large_work_items_status ON large_work_items (status);
CREATE INDEX IF NOT EXISTS idx_large_work_items_active_range ON large_work_items (start_date, end_date) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_large_work_item_teams_team ON large_work_item_teams (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_large_work_tasks_plan_sequence ON large_work_tasks (large_work_item_id, sequence);
CREATE INDEX IF NOT EXISTS idx_large_work_tasks_assigned_team_status ON large_work_tasks (assigned_team_id, status);

-- +goose Down
DROP INDEX IF EXISTS idx_large_work_tasks_assigned_team_status;
DROP INDEX IF EXISTS idx_large_work_tasks_plan_sequence;
DROP INDEX IF EXISTS idx_large_work_item_teams_team;
DROP INDEX IF EXISTS idx_large_work_items_active_range;
DROP INDEX IF EXISTS idx_large_work_items_status;
DROP INDEX IF EXISTS idx_large_work_items_date_range;
DROP INDEX IF EXISTS idx_large_work_items_owner_start_date;
DROP TABLE IF EXISTS large_work_tasks;
DROP TABLE IF EXISTS large_work_item_teams;
DROP TABLE IF EXISTS large_work_items;
