-- +goose Up
CREATE TABLE IF NOT EXISTS team_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES "Team"(id),
    created_by_user_id BIGINT NOT NULL REFERENCES "User"(id),
    title TEXT NOT NULL,
    work_type TEXT,
    start_date DATE NOT NULL,
    end_date DATE,
    work_time TEXT,
    location_text TEXT NOT NULL,
    pea_id BIGINT REFERENCES "Pea"(id),
    operation_center_id BIGINT REFERENCES "OperationCenter"(id),
    feeder_id BIGINT REFERENCES "Feeder"(id),
    station_id BIGINT REFERENCES "Station"(id),
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    daily_task_id BIGINT REFERENCES "TaskDaily"(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT team_plans_status_check CHECK (status IN ('planned', 'cancelled', 'completed')),
    CONSTRAINT team_plans_date_range_check CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_team_plans_team_start_date ON team_plans (team_id, start_date);
CREATE INDEX IF NOT EXISTS idx_team_plans_date_range ON team_plans (start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_team_plans_created_by ON team_plans (created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_team_plans_status ON team_plans (status);
CREATE INDEX IF NOT EXISTS idx_team_plans_active_range ON team_plans (start_date, end_date) WHERE deleted_at IS NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_team_plans_active_range;
DROP INDEX IF EXISTS idx_team_plans_status;
DROP INDEX IF EXISTS idx_team_plans_created_by;
DROP INDEX IF EXISTS idx_team_plans_date_range;
DROP INDEX IF EXISTS idx_team_plans_team_start_date;
DROP TABLE IF EXISTS team_plans;
